### ISSUE TITLE
Nuxt module improvements

### ISSUE THREAD

**Issue by pi0** [Lexpeartha/nuxt-xstate#5]
Hi. Following up https://github.com/nuxt/modules/pull/425, I've made a quick review of the module. And found one item could be improved:

- Possible values for `options.builder` are `webpack` and `vite` (https://github.com/Lexpeartha/nuxt-xstate/blob/e2ed60c3d327b0e9dc842e94aacb348364b002d9/src/module.ts#L23)

**Comment by Lexpeartha** [comment]
> - Possible values for `options.builder` are `webpack` and `vite`

Are you 100% positive on that? At first I wrote it like that, since type suggested it, however after some debugging and using console.log it turns out during runtime it actually has values of `@nuxt/vite-builder` and `@nuxt/webpack-builder`

Maybe it has been fixed in rc 7?

**Comment by pi0** [comment]
You are right. Option is [mapped](https://github.com/nuxt/framework/blob/076cb0d44f4f7d5bf73876bdf4e772b063b25c34/packages/schema/src/config/build.ts#L22) in schema. I guess will make a (unfortunately breaking change) later before final 3.0.0 release to keep it as simple `webpack` | `vite` as package names could change.

**Comment by Lexpeartha** [comment]
> You are right. Option is [mapped](https://github.com/nuxt/framework/blob/076cb0d44f4f7d5bf73876bdf4e772b063b25c34/packages/schema/src/config/build.ts#L22) in schema. I guess will make a (unfortunately breaking change) later before final 3.0.0 release to keep it as simple `webpack` | `vite` as package names could change. Will notify you to update condition with backward compatibility.

Values are still being mapped even in a stable version. Does that mean that it will stay like that?
